### ISSUE TITLE
Can't connect to ensime server

### ISSUE THREAD

**Issue by albertmichaelj** [ensime/ensime-emacs#245] opened 2015-09-22 17:07 UTC
Hi everyone,

I'm on OS X Yosemite 10.10.5, using Emacs 24.5.1, ensime version 20150915.1240 from elpa, and sbt version 0.13.7 from macports.

I used to be able to connect to the ensime server fine from my setup, but I haven't tried in about half a year, and now when I try to connect to the ensime server using `M-x ensime`, I get the following: 

```
Starting ENSIME server: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar:/Users/Michael/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar:/Users/Michael/.ivy2/cache/org.ensime/ensime_2.11/jars/ensime_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.ensime/server_2.11/jars/server_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.ensime/core_2.11/jars/core_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.4.jar:/Users/Michael/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.4.jar:/Users/Michael/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar:/Users/Michael/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.2.jar:/Users/Michael/.ivy2/cache/org.ensime/api_2.11/jars/api_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.scalariform/scalariform_2.11/jars/scalariform_2.11-0.1.7.jar:/Users/Michael/.ivy2/cache/com.github.stacycurl/pimpathon-core_2.11/jars/pimpathon-core_2.11-1.5.0.jar:/Users/Michael/.ivy2/cache/org.ensime/sexpress_2.11/jars/sexpress_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.parboiled/parboiled-scala_2.11/jars/parboiled-scala_2.11-1.1.7.jar:/Users/Michael/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.7.jar:/Users/Michael/.ivy2/cache/com.chuusai/shapeless_2.11/bundles/shapeless_2.11-2.2.5.jar:/Users/Michael/.ivy2/cache/com.h2database/h2/jars/h2-1.4.188.jar:/Users/Michael/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-2.1.0.jar:/Users/Michael/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/Users/Michael/.ivy2/cache/com.jolbox/bonecp/bundles/bonecp-0.8.0.RELEASE.jar:/Users/Michael/.ivy2/cache/com.google.guava/guava/bundles/guava-15.0.jar:/Users/Michael/.ivy2/cache/org.apache.commons/commons-vfs2/jars/commons-vfs2-2.0.jar:/Users/Michael/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.1.jar:/Users/Michael/.ivy2/cache/org.apache.maven.scm/maven-scm-api/jars/maven-scm-api-1.4.jar:/Users/Michael/.ivy2/cache/org.codehaus.plexus/plexus-utils/jars/plexus-utils-1.5.6.jar:/Users/Michael/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svnexe/jars/maven-scm-provider-svnexe-1.4.jar:/Users/Michael/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svn-commons/jars/maven-scm-provider-svn-commons-1.4.jar:/Users/Michael/.ivy2/cache/regexp/regexp/jars/regexp-1.3.jar:/Users/Michael/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-4.7.2.jar:/Users/Michael/.ivy2/cache/org.apache.lucene/lucene-analyzers-common/jars/lucene-analyzers-common-4.7.2.jar:/Users/Michael/.ivy2/cache/org.ow2.asm/asm-commons/jars/asm-commons-5.0.4.jar:/Users/Michael/.ivy2/cache/org.ow2.asm/asm-tree/jars/asm-tree-5.0.4.jar:/Users/Michael/.ivy2/cache/org.ow2.asm/asm/jars/asm-5.0.4.jar:/Users/Michael/.ivy2/cache/org.ow2.asm/asm-util/jars/asm-util-5.0.4.jar:/Users/Michael/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.11.4.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.12.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.3.12.jar:/Users/Michael/.ivy2/cache/org.scala-refactoring/org.scala-refactoring.library_2.11/jars/org.scala-refactoring.library_2.11-0.6.2.jar:/Users/Michael/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar:/Users/Michael/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.3.jar:/Users/Michael/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.3.jar:/Users/Michael/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.12.jar:/Users/Michael/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.12.jar:/Users/Michael/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.12.jar:/Users/Michael/.ivy2/cache/org.ensime/swank_2.11/jars/swank_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.ensime/jerk_2.11/jars/jerk_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/com.github.fommil/spray-json-shapeless_2.11/jars/spray-json-shapeless_2.11-1.1.0.jar:/Users/Michael/.ivy2/cache/io.spray/spray-json_2.11/bundles/spray-json_2.11-1.3.2.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-stream-experimental_2.11/jars/akka-stream-experimental_2.11-1.0.jar:/Users/Michael/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-http-core-experimental_2.11/jars/akka-http-core-experimental_2.11-1.0.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-parsing-experimental_2.11/jars/akka-parsing-experimental_2.11-1.0.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-http-experimental_2.11/jars/akka-http-experimental_2.11-1.0.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-http-spray-json-experimental_2.11/jars/akka-http-spray-json-experimental_2.11-1.0.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-http-xml-experimental_2.11/jars/akka-http-xml-experimental_2.11-1.0.jar -Xss2m -XX:+CMSClassUnloadingEnabled -Xms1536m -Xmx1536m -XX:MaxPermSize=384m -XX:ReservedCodeCacheSize=192m -Dfile.encoding=UTF8 -Densime.config=/Users/Michael/Documents/Projects/hello/.ensime org.ensime.server.Server
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
11:53:38.464 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
11:53:38.474 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
11:53:38.477 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
11:53:38.512 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/var/folders/zg/kt02lt3s3pg61fws3gc4jn780000gn/T/vfs_cache" as temporary files store.
11:53:38.544 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:49827
11:53:38.546 INFO  None o.e.s.PortUtil$ - creating portfile /Users/Michael/Documents/Projects/hello/.ensime_cache/port
11:53:38.546 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 49827
11:53:39.096 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Successfully bound to /127.0.0.1:49828
11:53:39.097 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
  OS : Mac OS X
  Java : Java HotSpot(TM) 64-Bit Server VM 25.60-b23, Java(TM) SE Runtime Environment 1.8.0_60-b27
  Scala : version 2.11.4
  Ensime : 0.9.10-SNAPSHOT
11:53:39.101 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1
11:53:39.102 ERROR None Server - Shutdown requested due to internal error: http endpoint failed to initialise: An ENSIME server might be open already for this project. If you are sure this is not the case, please delete /Users/Michael/Documents/Projects/hello/.ensime_cache/http and 
11:53:39.102 INFO  None Server - Shutting down the ActorSystem
11:53:39.102 INFO  None Server - Awaiting actor system termination
11:53:39.113 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Unbinding endpoint /127.0.0.1:49828
11:53:39.115 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Unbound endpoint /127.0.0.1:49828, stopping listener
11:53:39.116 INFO  akka://ENSIME/system/IO-TCP-STREAM/server-1-%2F127.0.0.1%3A0 a.a.LocalActorRef - Message [akka.io.Tcp$Unbound$] from Actor[akka://ENSIME/system/IO-TCP/selectors/$a/1#-604674877] to Actor[akka://ENSIME/system/IO-TCP-STREAM/server-1-%2F127.0.0.1%3A0#-649292646] was not delivered. [1] dead letters encountered. This logging can be tu
11:53:39.177 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/ensime-main/tcp-server#1452529907]] terminated
11:53:39.178 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Closing serverSocketChannel after being stopped
11:53:40.023 DEBUG EventStream a.e.EventStream - shutting down: StandardOutLogger started
11:53:40.047 INFO  None Server - Shutdown complete

Process *inferior-ensime-server-root*<2> exited abnormally with code 1
```

I've looked through other issues, but I haven't been able to solve this. Anybody have any ideas? Sbt is on my exec-path for emacs, and I've defined JDK_HOME.

Thanks for any help.

**Comment by albertmichaelj** [comment] 2015-09-22 17:11
By the way, this happens with the example project linked to at http://www.scala-sbt.org/0.13/tutorial/Hello.html with a fresh `sbt gen-ensime`. I get this the first time I run `M-x ensime` after generating the ensime file.

```
Starting ENSIME server: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar:/Users/Michael/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar:/Users/Michael/.ivy2/cache/org.ensime/ensime_2.11/jars/ensime_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.ensime/server_2.11/jars/server_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.ensime/core_2.11/jars/core_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.4.jar:/Users/Michael/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.4.jar:/Users/Michael/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar:/Users/Michael/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.2.jar:/Users/Michael/.ivy2/cache/org.ensime/api_2.11/jars/api_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.scalariform/scalariform_2.11/jars/scalariform_2.11-0.1.7.jar:/Users/Michael/.ivy2/cache/com.github.stacycurl/pimpathon-core_2.11/jars/pimpathon-core_2.11-1.5.0.jar:/Users/Michael/.ivy2/cache/org.ensime/sexpress_2.11/jars/sexpress_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.parboiled/parboiled-scala_2.11/jars/parboiled-scala_2.11-1.1.7.jar:/Users/Michael/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.7.jar:/Users/Michael/.ivy2/cache/com.chuusai/shapeless_2.11/bundles/shapeless_2.11-2.2.5.jar:/Users/Michael/.ivy2/cache/com.h2database/h2/jars/h2-1.4.188.jar:/Users/Michael/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-2.1.0.jar:/Users/Michael/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/Users/Michael/.ivy2/cache/com.jolbox/bonecp/bundles/bonecp-0.8.0.RELEASE.jar:/Users/Michael/.ivy2/cache/com.google.guava/guava/bundles/guava-15.0.jar:/Users/Michael/.ivy2/cache/org.apache.commons/commons-vfs2/jars/commons-vfs2-2.0.jar:/Users/Michael/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.1.jar:/Users/Michael/.ivy2/cache/org.apache.maven.scm/maven-scm-api/jars/maven-scm-api-1.4.jar:/Users/Michael/.ivy2/cache/org.codehaus.plexus/plexus-utils/jars/plexus-utils-1.5.6.jar:/Users/Michael/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svnexe/jars/maven-scm-provider-svnexe-1.4.jar:/Users/Michael/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svn-commons/jars/maven-scm-provider-svn-commons-1.4.jar:/Users/Michael/.ivy2/cache/regexp/regexp/jars/regexp-1.3.jar:/Users/Michael/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-4.7.2.jar:/Users/Michael/.ivy2/cache/org.apache.lucene/lucene-analyzers-common/jars/lucene-analyzers-common-4.7.2.jar:/Users/Michael/.ivy2/cache/org.ow2.asm/asm-commons/jars/asm-commons-5.0.4.jar:/Users/Michael/.ivy2/cache/org.ow2.asm/asm-tree/jars/asm-tree-5.0.4.jar:/Users/Michael/.ivy2/cache/org.ow2.asm/asm/jars/asm-5.0.4.jar:/Users/Michael/.ivy2/cache/org.ow2.asm/asm-util/jars/asm-util-5.0.4.jar:/Users/Michael/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.11.4.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.12.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.3.12.jar:/Users/Michael/.ivy2/cache/org.scala-refactoring/org.scala-refactoring.library_2.11/jars/org.scala-refactoring.library_2.11-0.6.2.jar:/Users/Michael/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar:/Users/Michael/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.3.jar:/Users/Michael/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.3.jar:/Users/Michael/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.12.jar:/Users/Michael/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.12.jar:/Users/Michael/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.12.jar:/Users/Michael/.ivy2/cache/org.ensime/swank_2.11/jars/swank_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/org.ensime/jerk_2.11/jars/jerk_2.11-0.9.10-SNAPSHOT.jar:/Users/Michael/.ivy2/cache/com.github.fommil/spray-json-shapeless_2.11/jars/spray-json-shapeless_2.11-1.1.0.jar:/Users/Michael/.ivy2/cache/io.spray/spray-json_2.11/bundles/spray-json_2.11-1.3.2.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-stream-experimental_2.11/jars/akka-stream-experimental_2.11-1.0.jar:/Users/Michael/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-http-core-experimental_2.11/jars/akka-http-core-experimental_2.11-1.0.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-parsing-experimental_2.11/jars/akka-parsing-experimental_2.11-1.0.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-http-experimental_2.11/jars/akka-http-experimental_2.11-1.0.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-http-spray-json-experimental_2.11/jars/akka-http-spray-json-experimental_2.11-1.0.jar:/Users/Michael/.ivy2/cache/com.typesafe.akka/akka-http-xml-experimental_2.11/jars/akka-http-xml-experimental_2.11-1.0.jar -Xss2m -XX:+CMSClassUnloadingEnabled -Xms1536m -Xmx1536m -XX:MaxPermSize=384m -XX:ReservedCodeCacheSize=192m -Dfile.encoding=UTF8 -Densime.config=/Users/Michael/Documents/Projects/hello/.ensime org.ensime.server.Server
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
12:10:45.412 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
12:10:45.420 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
12:10:45.422 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
12:10:45.455 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/var/folders/zg/kt02lt3s3pg61fws3gc4jn780000gn/T/vfs_cache" as temporary files store.
12:10:45.488 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:50431
12:10:45.490 INFO  None o.e.s.PortUtil$ - creating portfile /Users/Michael/Documents/Projects/hello/.ensime_cache/port
12:10:45.490 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 50431
12:10:46.004 INFO  None o.e.i.DatabaseService - creating the search database
12:10:46.081 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Successfully bound to /127.0.0.1:50432
12:10:46.090 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
  OS : Mac OS X
  Java : Java HotSpot(TM) 64-Bit Server VM 25.60-b23, Java(TM) SE Runtime Environment 1.8.0_60-b27
  Scala : version 2.11.4
  Ensime : 0.9.10-SNAPSHOT
12:10:46.092 INFO  akka://ENSIME/system/IO-TCP/selectors/$a/1 o.e.s.PortUtil$ - creating portfile /Users/Michael/Documents/Projects/hello/.ensime_cache/http
12:10:46.092 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1
12:10:46.185 WARN  None c.j.b.BoneCPConfig - JDBC username was not set in config!
12:10:46.186 WARN  None c.j.b.BoneCPConfig - JDBC password was not set in config!
12:10:46.536 INFO  None o.e.i.SearchService - removing 0 stale files from the index
12:10:46.545 INFO  None o.e.i.ClassfileWatcher - Setting up new file watchers
12:10:46.585 DEBUG None o.e.i.SearchService - indexing file:///Users/Michael/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.4.jar
12:10:46.585 DEBUG None o.e.i.SearchService - indexing file:///Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/rt.jar
12:10:47.734 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent in state startup
12:10:50.656 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - New connection accepted
12:10:50.667 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Connection from localhost
12:10:50.668 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Client connected - active clients now: 1
12:10:50.710 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/1 o.e.s.RequestHandler - ConnectionInfoReq
12:10:50.711 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message ConnectionInfoReq
12:10:50.713 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/1 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),0.8.17) in state receive
12:11:00.398 DEBUG None o.e.i.SearchService - committing index to disk...
12:11:00.761 DEBUG None o.e.i.SearchService - ...done committing index
12:11:00.763 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - indexed 4 and removed 0
```

**Comment by fommil** [comment] 2015-09-22 17:20
This last message looks like it works again, is that right?

**Comment by albertmichaelj** [comment] 2015-09-22 17:22
No, the server never actually connects. If I try to do anything such as `C-c C-c a` gets me the message `Not connected. M-x ensime to connect.`

**Comment by fommil** [comment] 2015-09-22 17:24
I think it is connecting, but maybe the client is dropping some message.

**Comment by albertmichaelj** [comment] 2015-09-22 17:24
How do I test this?

**Comment by fommil** [comment] 2015-09-22 17:34
I'll try locally

**Comment by fommil** [comment] 2015-09-22 19:22
I think this is a dupe of FAQ https://github.com/ensime/ensime-server/issues/714 closing unless you have a github project that demonstrates the problem.

**Closed by fommil** 2015-09-22 19:22 UTC

**Comment by albertmichaelj** [comment] 2015-09-22 19:36
You're right, with that specific example, I didn't have a maven source layout and that was the problem. However, I have now moved the `hw.scala` script from the link that I have posted above into a directory in a new project with a maven source layout, and now emacs is freezing with a `waiting for connection-info` message as soon as I try to connect to the ensime server. 

This was actually happening with the full project I was trying to look at as well, but I wanted to have a minimal example. I've let the `waiting for connection-info

**Comment by fommil** [comment] 2015-09-22 19:40
you can always do `ESC ESC ESC` to unblock emacs. You might now be seeing the OS X emacs bug we seen a few months ago, have a search in the tickets for the resolution of that. I thought we documented it, maybe not.

**Comment by albertmichaelj** [comment] 2015-09-22 19:57
Maybe it is the same problem, but I found ticket #220, but it doesn't give a solution. What is the recommended course of action? 

I also used betehess's trick of not having any scala files open and trying to connect to the ensime server, but then, while it seems like the server has started (the *inferior-ensime-server-root* buffer doesn't indicate that it exited abnormally, and if I delete files in the directory, the buffer picks it up), if I actually try `C-c C-c a` in the buffer, it gives me the message that I'm not connected. If I try `M-x ensime` again, it looks like it opens up a new connection (new *inferior-ensime-server-root* buffer), but I'm still disconnected.

Something is still broken, but I'm not sure what. I tried using Emacs 24.4 instead of 24.5.1 in case there was a specific emacs version issue, but I'm seeing the same result. Any suggestions?

**Comment by fommil** [comment] 2015-09-22 20:04
the recommended solution is from noelwelsh regarding the exact emacs to use

**Comment by albertmichaelj** [comment] 2015-09-22 20:11
In ticket #220, betehess says specifically that the emacs version that noelwelsh recommends did not solve his problem. So, that isn't a solution based on the thread (it didn't solve betehess's problems).

Does anyone have any suggestions?
