### ISSUE TITLE
Imports added in the wrong place

### ISSUE THREAD

**Issue by Vifon** [ensime/ensime-emacs#197] opened 2015-07-14 17:16 UTC
**Steps to reproduce**

1. Create a file with an import in the very first line, for example `scala.collection.mutable.Set`.
2. Add a new import using <kbd>C-c C-r t</kbd> that is will be places lexicographically in the line above the previous import (the first import now is in the second line and the new one is in the first line). For example `javax.swing.JPanel`.

**What happens**

The file looks like this:

```Scala
iimport javax.swing.JPanel
mport scala.collection.mutable.Set
```

**What was expected**

The file should look like this:

```Scala
import javax.swing.JPanel
import scala.collection.mutable.Set
```

**Comment by fommil** [comment] 2015-07-14 17:49
Yup, that's a bug alright. Would you like us to help you fix it?

**Comment by Vifon** [comment] 2015-07-14 20:53
If it's within my reach, yeah.

After a quick analysis, I think it's not in the Emacs client after all but in the ENSIME server. Could someone else confirm this?

**Comment by aemoncannon** [comment] 2015-07-14 21:01
I believe in fact the code for inserting imports is in emacs.

**Comment by fommil** [comment] 2015-07-14 21:02
hmm, I thought it was the client that did this sort of thing but I can believe that if its a refactoring.

https://github.com/ensime/ensime-server/blob/master/core/src/main/scala/org/ensime/core/Refactoring.scala#L207

might be an upstream bug!

You could consider writing a test case here to get started

https://github.com/ensime/ensime-server/blob/master/core/src/it/scala/org/ensime/core/RefactoringHandlerSpec.scala

I'll move it to the server if you can confirm which side its on.

**Comment by fommil** [comment] 2015-07-14 21:10
https://github.com/ensime/ensime-emacs/blob/master/ensime-refactor.el#L134

**Comment by Vifon** [comment] 2015-07-19 22:03
I could use some more help. I've been using Scala for literally two weeks. How do I run the tests so that I know that the one I'm going to add works (or in this case: fails).

**Comment by fommil** [comment] 2015-07-20 08:11
Probably something like

`core/it:test-only *RefactoringHandlerSpec -- -z "import on first line"`

* `core` because this is the core module
* `it:` because the tests are in the `IntegrationTests` config
* `test-only` to restrict testing to the next regex pattern
* `*RefactoringHandlerSpec` to only run specs matching this pattern
* `--` to pass additional parameters
* `-z "foo"` to restrict to only the tests with this substring

**Comment by Vifon** [comment] 2015-07-21 09:18
At the `sbt` prompt, right? Are there any dependencies to manually supply? After calling `sbt 'core/it:test-only *RefactoringHandlerSpec'` I get this:

```
[info] Loading global plugins from /home/vifon/.sbt/0.13/plugins
[info] Loading project definition from /home/vifon/src/ensime-server/project
[info] Set current project to ensime (in build file:/home/vifon/src/ensime-server/)
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] RefactoringHandlerSpec:
[info] RefactoringHandler
[info] Exception encountered when attempting to run a suite with class name: org.ensime.core.RefactoringHandlerSpec *** ABORTED ***
[info]   java.lang.ExceptionInInitializerError:
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$$anonfun$withEnsimeConfig$1.apply(EnsimeConfigFixture.scala:128)
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$$anonfun$withEnsimeConfig$1.apply(EnsimeConfigFixture.scala:128)
[info]   at pimpathon.FileUtils$$anonfun$withTempDirectory$1.apply(file.scala:108)
[info]   at pimpathon.FileUtils$$anonfun$withTempDirectory$1.apply(file.scala:108)
[info]   at pimpathon.FileUtils$$anonfun$withTempFile$1.apply(file.scala:113)
[info]   at pimpathon.FileUtils$$anonfun$withTempFile$1.apply(file.scala:113)
[info]   at pimpathon.any$AnyPimps$.calc$extension(any.scala:12)
[info]   at pimpathon.FileUtils.withTempFile(file.scala:113)
[info]   at pimpathon.FileUtils.withTempDirectory(file.scala:108)
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$class.withEnsimeConfig(EnsimeConfigFixture.scala:127)
[info]   at org.ensime.core.RefactoringHandlerSpec.withEnsimeConfig(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.fixture.IsolatedSourceResolverFixture$class.withSourceResolver(SourceResolverFixture.scala:21)
[info]   at org.ensime.core.RefactoringHandlerSpec.withSourceResolver(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.fixture.IsolatedSearchServiceFixture$class.withSearchService(SearchServiceFixture.scala:10)
[info]   at org.ensime.core.RefactoringHandlerSpec.withSearchService(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.fixture.IsolatedAnalyzerFixture$$anonfun$withAnalyzer$1$$anonfun$apply$1.apply(AnalyzerFixture.scala:32)
[info]   at org.ensime.fixture.IsolatedAnalyzerFixture$$anonfun$withAnalyzer$1$$anonfun$apply$1.apply(AnalyzerFixture.scala:30)
[info]   at org.ensime.fixture.IsolatedTestKitFixture$class.withTestKit(TestKitFixture.scala:39)
[info]   at org.ensime.core.RefactoringHandlerSpec.withTestKit(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.fixture.IsolatedAnalyzerFixture$$anonfun$withAnalyzer$1.apply(AnalyzerFixture.scala:30)
[info]   at org.ensime.fixture.IsolatedAnalyzerFixture$$anonfun$withAnalyzer$1.apply(AnalyzerFixture.scala:29)
[info]   at org.ensime.fixture.IsolatedEnsimeVFSFixture$class.withVFS(EnsimeVFSFixture.scala:16)
[info]   at org.ensime.core.RefactoringHandlerSpec.withVFS(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.fixture.IsolatedAnalyzerFixture$class.withAnalyzer(AnalyzerFixture.scala:29)
[info]   at org.ensime.core.RefactoringHandlerSpec.withAnalyzer(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.core.RefactoringHandlerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(RefactoringHandlerSpec.scala:24)
[info]   at org.ensime.core.RefactoringHandlerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RefactoringHandlerSpec.scala:24)
[info]   at org.ensime.core.RefactoringHandlerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RefactoringHandlerSpec.scala:24)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpec.run(WordSpec.scala:1881)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:294)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:284)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
[info]   Cause: java.lang.IllegalArgumentException: requirement failed: the .ensime file must exist to run the integration tests.Type 'sbt gen-ensime' to create it
[info]   at scala.Predef$.require(Predef.scala:219)
[info]   at org.ensime.fixture.EnsimeConfigFixture$.<init>(EnsimeConfigFixture.scala:33)
[info]   at org.ensime.fixture.EnsimeConfigFixture$.<clinit>(EnsimeConfigFixture.scala)
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$$anonfun$withEnsimeConfig$1.apply(EnsimeConfigFixture.scala:128)
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$$anonfun$withEnsimeConfig$1.apply(EnsimeConfigFixture.scala:128)
[info]   at pimpathon.FileUtils$$anonfun$withTempDirectory$1.apply(file.scala:108)
[info]   at pimpathon.FileUtils$$anonfun$withTempDirectory$1.apply(file.scala:108)
[info]   at pimpathon.FileUtils$$anonfun$withTempFile$1.apply(file.scala:113)
[info]   at pimpathon.FileUtils$$anonfun$withTempFile$1.apply(file.scala:113)
[info]   at pimpathon.any$AnyPimps$.calc$extension(any.scala:12)
[info]   at pimpathon.FileUtils.withTempFile(file.scala:113)
[info]   at pimpathon.FileUtils.withTempDirectory(file.scala:108)
[info]   at org.ensime.fixture.IsolatedEnsimeConfigFixture$class.withEnsimeConfig(EnsimeConfigFixture.scala:127)
[info]   at org.ensime.core.RefactoringHandlerSpec.withEnsimeConfig(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.fixture.IsolatedSourceResolverFixture$class.withSourceResolver(SourceResolverFixture.scala:21)
[info]   at org.ensime.core.RefactoringHandlerSpec.withSourceResolver(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.fixture.IsolatedSearchServiceFixture$class.withSearchService(SearchServiceFixture.scala:10)
[info]   at org.ensime.core.RefactoringHandlerSpec.withSearchService(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.fixture.IsolatedAnalyzerFixture$$anonfun$withAnalyzer$1$$anonfun$apply$1.apply(AnalyzerFixture.scala:32)
[info]   at org.ensime.fixture.IsolatedAnalyzerFixture$$anonfun$withAnalyzer$1$$anonfun$apply$1.apply(AnalyzerFixture.scala:30)
[info]   at org.ensime.fixture.IsolatedTestKitFixture$class.withTestKit(TestKitFixture.scala:39)
[info]   at org.ensime.core.RefactoringHandlerSpec.withTestKit(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.fixture.IsolatedAnalyzerFixture$$anonfun$withAnalyzer$1.apply(AnalyzerFixture.scala:30)
[info]   at org.ensime.fixture.IsolatedAnalyzerFixture$$anonfun$withAnalyzer$1.apply(AnalyzerFixture.scala:29)
[info]   at org.ensime.fixture.IsolatedEnsimeVFSFixture$class.withVFS(EnsimeVFSFixture.scala:16)
[info]   at org.ensime.core.RefactoringHandlerSpec.withVFS(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.fixture.IsolatedAnalyzerFixture$class.withAnalyzer(AnalyzerFixture.scala:29)
[info]   at org.ensime.core.RefactoringHandlerSpec.withAnalyzer(RefactoringHandlerSpec.scala:9)
[info]   at org.ensime.core.RefactoringHandlerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(RefactoringHandlerSpec.scala:24)
[info]   at org.ensime.core.RefactoringHandlerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RefactoringHandlerSpec.scala:24)
[info]   at org.ensime.core.RefactoringHandlerSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RefactoringHandlerSpec.scala:24)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
[info]   at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
[info]   at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
[info]   at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
[info]   at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1424)
[info]   at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpec.run(WordSpec.scala:1881)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:294)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:284)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)
[info] ScalaTest
[info] Run completed in 1 second, 576 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 1
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error]         org.ensime.core.RefactoringHandlerSpec
[error] (core/it:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4 s, completed Jul 21, 2015 11:16:40 AM
```

**Comment by fommil** [comment] 2015-07-21 09:48
oh, sorry, for our integration tests you need to have typed `sbt gen-ensime` to produce the `.ensime` file.

**Comment by Vifon** [comment] 2015-07-22 16:30
I've managed to run the tests. I'm trying to add a new one. This is what I've got so far:

```Scala
    "add imports on the first line" in withAnalyzer { (dir, analyzerRef) =>
      val content = contents(
        "import scala.collection.mutable.Set"
      )
      val analyzer = analyzerRef.underlyingActor

      val formatted = analyzer.handleRefactorExec(
        new ExecRefactorReq(0, RefactorType.AddImport)) // FIXME
      val expectedContents = contents(
        "import javax.swing.JPanel",
        "import scala.collection.mutable.Set"
      )
      assert(formatted === expectedContents)
    }
```

Obviously "0" is not a proper procId. How can I create an ENSIME process attached to the test file?

**Comment by fommil** [comment] 2015-07-22 16:37
you need to query for "prepare refactor" first, I think. But you also need to have written this out as a file to disk for the integration test to work, other tests should be a good template.

**Comment by Vifon** [comment] 2015-07-22 17:38
I've got the file on disk now (by copying some more code from the other test cases) but I honestly have no idea how to invoke the refactoring procedure.

**Comment by fommil** [comment] 2015-07-22 18:05
@Vifon I don't actually know either, so lets try to work it out :-) the API s defined in incoming.scala and will end up in the analyzer actor. From there, you should be able to see which method is called. I suspect it's two phase: a prepare refactor followed by a perform refactor.

**Comment by Vifon** [comment] 2015-07-22 22:07
Thank's for your help so far. I've managed to get to this point: https://gist.github.com/Vifon/b9e6a09c4f221d414a2b

The new import surprisingly is not placed lexicographically, just inserted after the first import. I don't see the code responsible for the new import placement on the Emacs side so it must be there somewhere.
Secondly, I suppose I shouldn't use `handleFormatFile` here but I don't know how to get the refactored file content otherwise.

**Comment by fommil** [comment] 2015-07-23 06:45
Hehe, you have the file on disk she just slurp it up,I should imagine the other tests also do a validation at the end.

**Comment by fommil** [comment] 2015-07-23 12:47
@Vifon some small comments:

1. I belive `handleRefactorPrepareRequest` should give you the `procId`
2. use `readSrcFile` to read the contents from the disk

**Comment by Vifon** [comment] 2015-07-25 19:17
`handleRefactorPrepareRequest` returns `Unit` and takes `PrepareRefactorReq` which already needs a `procId`. I believe `procId` is just an identifier of the performed operation. If it matches in both request and perform, it should be fine as long as there is only a single operation at a time.

Thanks for `readSrcFile`, it does exactly what I needed.

Still, However I call the refactoring-related functions, the new import is always added after the first one. When I do the same from Emacs, it's added according to the lexicographical order. I've checked again the Emacs side of Ensime and all it does is passing the call to the Ensime server. I've also tried calling `OrganizeImports` afterwards, to no avail.

Is it ok that we're discussing it here? Should I close this issue and open one in the Ensime server issue tracker?

**Comment by fommil** [comment] 2015-07-25 19:46
@Vifon yeah, don't worry about where the discussion is :smile: we can always pick up the server side discussion in a PR if you get that far. But I'm confused, are you saying that the server is behaving OK but emacs is rearranging things? It might be worth writing this as an emacs integration test in that case, it would catch the entire workflow. A lot harder to debug, but it's a start.

**Comment by Vifon** [comment] 2015-07-25 19:58
It also might be the case that the current Ensime server (from Git) is behaving ok and the one I am using is not. It would be plausible if the behavior was "correct" vs "incorrect". But it is "sorted and incorrect" vs "not sorted and N/A because it's never inserted in the first line".

I have Ensime installed using this line in my `~/.sbt/0.13/plugins/plugins.sbt`: `addSbtPlugin("org.ensime" % "ensime-sbt" % "0.1.7")`. How can I select which Ensime version to use in Emacs?

**Comment by fommil** [comment] 2015-07-25 20:14
@Vifon what version of scala is your project using? If you're using 2.11, you'll be using `master` unless you've not updated from MELPA in ages.

**Comment by Vifon** [comment] 2015-07-25 20:29
"Project"... It's a glorified hello world. ;)
From `.ensime`: `:scala-version "2.10.4"`

I've just added `scalaVersion in ThisBuild := "2.11.7"` to my `build.sbt`, regenerated `.ensime` and rechecked the issue. Still there. :/

`ensime-server-version` in Emacs is set to `"0.9.10-SNAPSHOT"`.

**Comment by fommil** [comment] 2015-07-25 21:21
interesting. maybe this is an emacs bug afterall instead of server. Can you push your server changes to a repo somewhere so I can have a look? The next thing to do is to change the `simple` project in `testing` to have a file like your one and then edit `BasicWorkflow` to do an import in that file.

**Comment by Vifon** [comment] 2015-07-25 21:31
Sure: https://github.com/Vifon/ensime-server/commit/57a6c61c15850cc2ee8976497cd208b626194f4f

**Comment by fommil** [comment] 2015-07-25 21:49
ok, well we can't have too many tests so if you remove the `println`s we'll accept that as a PR. Sounds like we need to start looking at the interaction with emacs :-/

**Comment by Vifon** [comment] 2015-07-25 21:57
But it's failing. The expected value is sorted, the actual value is not.

**Comment by fommil** [comment] 2015-07-25 22:13
@Vifon aah, ok, so you're confirming a server bug. sorry, I got confused and thought we didn't know where in the chain the bug was. That's good, it means the problem is localised. OK, now you can close this ticket and raise a new one on the server include the test in the ticket as a minimal failing case and we'll help you try to fix it in the server. Good way to learn Scala, right? :smile:

**Closed by fommil** 2015-07-25 22:13 UTC
Labels: Bug

**Comment by Vifon** [comment] 2015-07-25 22:27
I think these are two separate problems:

1. The imports added in the first line (according to the lexicographical order) are added starting with the 1st file byte instead of the 0th one (counting from 0), resulting in the behavior described in my original issue.
2. We do not know how to add the import in the same way (with sorting and everything). I find it extremely improbable that the functionality of sorting the added imports was removed at some point, so it must be us.

I'll report the 1st issue while pointing out the 2nd regarding the code I'll link. I'll do it tomorrow.

Thanks a lot. :)

**Comment by fommil** [comment] 2015-07-25 22:45
I bet you the code that does this looks for a newline and adds one.

**Comment by Vifon** [comment] 2015-07-26 20:58
Actually I've just found a report of the exact same issue: https://github.com/ensime/ensime-server/issues/1029

No point in opening a second ticket, I suppose. I'll just link this thread there for reference.
