### ISSUE TITLE
ensime keeps restarting if a file is not found

### ISSUE THREAD

**Issue by oscar-broman** [ensime/ensime-emacs#283] opened 2015-11-05 14:27 UTC
I created a buffer called `Test.scala` and ensime kept restarting until I saved it.

```
java.io.FileNotFoundException: source file '/Users/oscar/project/src/main/scala/package/Test.scala' could not be found
	at scala.tools.nsc.Global.getSourceFile(Global.scala:372) ~[scala-compiler-2.11.7.jar:na]
	at org.ensime.core.RichCompilerControl$class.createSourceFile(RichPresentationCompiler.scala:177) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.RichPresentationCompiler.createSourceFile(RichPresentationCompiler.scala:198) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer.createSourceFile(Analyzer.scala:290) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:236) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:152) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.Analyzer$$anonfun$ready$1.applyOrElse(Analyzer.scala:149) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.11-2.3.14.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.14.jar:na]
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.7.jar:na]
	at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]
	at org.ensime.core.Analyzer.aroundReceive(Analyzer.scala:41) ~[core_2.11.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
```

**Comment by aemoncannon** [comment] 2015-11-05 16:01
Looks like we're requesting semantic highlighting for a file that hasn't been written to disk. 
* In the short term, we should just skip highlighting such files. That's a small elisp fix. Care to PR?
* Longterm we want to modify the server accept SourceFileInfo for SymbolDesignationsReq, so we can do things like send source file contents, or source written to temp file (as we do with completions).
FYI, @edani

**Comment by fommil** [comment] 2015-11-05 16:06
Yeah, I remember this. I think it was one of the reasons for the sit-for hack.

**Comment by aemoncannon** [comment] 2015-11-05 16:30
@fommil
RE: sit-for hack. It looks like the problem is that we do a bunch of work
in Project preStart, so the ConnectionInfoReq doesn't get serviced for a
while. How hard would it be to ad a prePreStart, that just services for
ConnectionInfoReq and then kicks to preStart afterward. Would have to queue
any other messages in the mean time.

**Comment by fommil** [comment] 2015-11-05 16:52
@aemoncannon I'm much happier with the suggestion above of dropping queries if the buffer isn't persisted to disk yet. The real fix is as you suggest. I'm very keen **not** to go back to that evil hack of doom. There is a special place in hell with my name on it.

**Comment by aemoncannon** [comment] 2015-11-05 16:54
Haha. Here you are, @fommil. sit-for eternity.

**Comment by fommil** [comment] 2015-11-05 16:55
LOL only person frozen in hell.

**Comment by rahulkmr** [comment] 2015-11-08 19:28
I am facing the same issue, or at least I think I am.

Emacs version:
    24.5.1


Operating system:
    Ubuntu 15.04


Package versions:
    ensime             20151104.2001 installed             ENhanced Scala Interaction Mode for Emacs
    scala-mode2        20150617.2350 installed             Major mode for editing Scala >= 2.9


Package configuration:
    (require 'ensime)
    (require 'scala-mode2)
    (add-hook 'scala-mode-hook 'ensime-scala-mode-hook)
    (add-hook 'scala-mode-hook #'yas-minor-mode)


Error message:
    Asynchronous RPC Aborted: file(s): "/home/rahul/musings/scala.new/src/main/scala/line_count.scala" do not exist

    Initializing Analyzer. Please wait...
    ENSIME ready. Let the hacking commence!
    Initializing Analyzer. Please wait...
    ENSIME ready. Hacks and glory await!
    Initializing Analyzer. Please wait...
    ENSIME ready. Find closure!
    Initializing Analyzer. Please wait...
    ENSIME ready. Hack and be merry!
    Initializing Analyzer. Please wait...
    ENSIME ready. Hacks and glory await!
    Initializing Analyzer. Please wait...
    ENSIME ready. Hack and be merry!


Steps to reproduce:

1. Open emacs. Start ensime with `M-x ensime` with a configured .ensime.

ensime starts fine and works with saved files.

2. Try to open a new file `C-x C-f`. The new buffer opens and ensime goes berserk with the message.


Cause:
Not sure.


Workaround:
Save the buffer right after creating it. After a while, emacs becomes non-responsive and saving won't work.


Full trace:

    00:54:48.336 ERROR akka://ENSIME/user/ensime-main/project/scalac a.a.OneForOneStrategy - source file '/home/rahul/musings/scala.new/src/main/scala/blah.scala' could not be found
    java.io.FileNotFoundException: source file '/home/rahul/musings/scala.new/src/main/scala/blah.scala' could not be found
        at scala.tools.nsc.Global.getSourceFile(Global.scala:372) ~[scala-compiler-2.11.7.jar:na]
        at org.ensime.core.RichCompilerControl$class.createSourceFile(RichPresentationCompiler.scala:213) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.RichPresentationCompiler.createSourceFile(RichPresentationCompiler.scala:234) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer.createSourceFile(Analyzer.scala:290) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:236) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:152) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
        at org.ensime.core.Analyzer$$anonfun$ready$1.applyOrElse(Analyzer.scala:149) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.11-2.3.14.jar:na]
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.14.jar:na]
        at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.7.jar:na]
        at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.14.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]
        at org.ensime.core.Analyzer.aroundReceive(Analyzer.scala:41) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
    00:54:48.432 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent in state startup
    00:54:48.446 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/88 o.e.s.RequestHandler - SymbolDesignationsReq(/home/rahul/musings/scala.new/src/main/scala/fact.scala,0,143,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbol, ObjectSymbol, PackageSymbol
    00:54:48.447 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message SymbolDesignationsReq(/home/rahul/musings/scala.new/src/main/scala/fact.scala,0,143,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbol, Ob
    00:54:48.447 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message SymbolDesignationsReq(/home/rahul/musings/scala.new/src/main/scala/fact.scala,0,143,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbol, Ob
    00:54:48.452 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/89 o.e.s.RequestHandler - SymbolDesignationsReq(/home/rahul/musings/scala.new/src/main/scala/line_count.scala,0,0,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbol, ObjectSymbol, PackageSy
    00:54:48.452 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message SymbolDesignationsReq(/home/rahul/musings/scala.new/src/main/scala/line_count.scala,0,0,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbol
    00:54:48.455 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/90 o.e.s.RequestHandler - SymbolDesignationsReq(/home/rahul/musings/scala.new/src/main/scala/blah.scala,0,0,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbol, ObjectSymbol, PackageSymbol, 
    00:54:48.455 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message SymbolDesignationsReq(/home/rahul/musings/scala.new/src/main/scala/blah.scala,0,0,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbol, Obje
    00:54:48.538 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message SymbolDesignationsReq(/home/rahul/musings/scala.new/src/main/scala/line_count.scala,0,0,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbol
    00:54:48.539 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/88 o.e.s.RequestHandler - received handled message SymbolDesignations(/home/rahul/musings/scala.new/src/main/scala/fact.scala,List(SymbolDesignation(25,26,ParamSymbol), SymbolDesignation(28,34,ClassSymbol), SymbolDesignation(37,43,ClassSymbol), SymbolDesignation(56,58,Operato
    00:54:48.540 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/89 o.e.s.RequestHandler - received handled message SymbolDesignations(/home/rahul/musings/scala.new/src/main/scala/line_count.scala,List()) in state receive
    00:54:48.540 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message SymbolDesignationsReq(/home/rahul/musings/scala.new/src/main/scala/blah.scala,0,0,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbol, Obje

**Comment by fommil** [comment] 2015-11-08 19:37
yeah, get hacking in the emacs code :smile: should be a simple fix to not return the `ensime-connection` if the current buffer is not tied to a file on disk: https://github.com/ensime/ensime-emacs/blob/master/ensime-client.el#L140

**Comment by rahulkmr** [comment] 2015-11-08 20:08
What should I be doing? Just checking for file-exists doesn't seem to solve it.

```
(defun ensime-connection-or-nil ()
  "Return the connection to use for ENSIME interaction in the current buffer.
  Return nil if there's no connection.
  * In most code we prefer (ensime-connection), which raises an error if
  the connection is not present."
  (if (file-exists-p (buffer-file-name))
    (progn
      (or (ensime-conn-if-alive ensime-dispatching-connection)
          (ensime-conn-if-alive ensime-buffer-connection)
          (-when-let (conn (ensime-conn-if-alive
                             (or (ensime-owning-connection-for-source-file
                                   ;; supports files or directories (e.g. dired)
                                   (or buffer-file-name default-directory))
                                 (ensime-owning-connection-for-rootdir default-directory))))
                     ;; Cache the connection so lookup is fast next time.
                     (setq ensime-buffer-connection conn)
                     conn)))
    nil
    ))
```


>  not return the ensime-connection if the current buffer is not tied to a file on disk

Do you mean some sort of busy wait?

**Comment by aemoncannon** [comment] 2015-11-08 20:11
See above PR for a simple fix (sorry to step on your toes, @rahulkmr)

**Comment by aemoncannon** [comment] 2015-11-08 20:12
Generally speaking we do want to support unwritten files, but at the moment the server doesn't support it for semantic highlighting.

**Comment by aemoncannon** [comment] 2015-11-08 20:13
For example, completion and typechecking work fine for unwritten files.

**Comment by rahulkmr** [comment] 2015-11-08 20:20
Thanks @aemoncannon I am unfamiliar with the ensime codebase and elisp in general. It would have taken me a lot of time to find what to fix and fix it.

Is the fix working for you? I made your fix in ensime-20151104.2001/ensime-semantic-highlight.el, restarted emacs and ran ensime which ran an update. But when I try to open a new buffer, it does the same dance again.

**Comment by fommil** [comment] 2015-11-08 20:26
@rahulkmr just as a quick review of your code, I would have preferred to put the check in an additional `and` statement, instead of an `if` block. No need for a `progn`. I'd go with Aemon's fix though, as you'll still get typechecking and so on that way.

**Comment by fommil** [comment] 2015-11-08 20:27
@rahulkmr either delete the `ensime-semantic-highlight.elc` or use the setting `(setq load-prefer-newer t)` (but be aware that the latter might break your emacs on Debian as a result of a daylight savings bug that they introduced! Amateurs...)

**Comment by rahulkmr** [comment] 2015-11-08 20:32
Thanks @fommil Deleting elc did the trick. 

Now I get this message

> Asynchronous RPC Aborted: file(s): "/home/rahul/musings/scala.new/src/main/scala/blah.scala" do not exist

But completion and typechecking works.


>  No need for a progn

Yep. Didn't notice it already is under (or ...)

**Comment by aemoncannon** [comment] 2015-11-09 16:37
RE: Asynchronous RPC Aborted
Any indication of what rpc is being aborted there?

**Comment by aemoncannon** [comment] 2015-11-09 16:42
@fommil
Related: what's the suggested way to do a protocol update? How about:
1 introduce rpc-symbol-designations-v2 on server.
2  introduce calls in emacs client, assuming emacs client update will force a server update

**Comment by edani** [comment] 2015-11-09 16:49
@aemoncannon The way you describe usually works. Also it works well to have the emacs client check the server's protocol version to decide which version of the call to use.

**Comment by fommil** [comment] 2015-11-09 17:01
yeah, the protocol version check is a good one, although I'm happy removing the checks after some grace time as update to the client do invoke an update to the server and we can reasonably expect the user to have a network connection to update ENSIME in timeframes of about a month.

Its much less of an issue now since we're cross building 2.10 and 2.11 on the same branch, and dropped 2.9 support.

**Comment by rahulkmr** [comment] 2015-11-09 17:17
@aemoncannon 

> Any indication of what rpc is being aborted there?

I searched for 'Asynchronous RPC' in the plugin code. 

    % ▶ ag "Asynchronous RPC" .
    ensime-client.el
    860:     (message "Asynchronous RPC Aborted: %s" reason)))

The function at 860 is 

    % ▶ ruby -lane 'print $.,"\t", $_ if (846..865) === $.' ensime-client.el               
    846     (defun ensime-eval-async (sexp &optional cont)
    847       "Evaluate EXPR on the superior Lisp and call CONT with the result."
    848       (ensime-rex (cont (buffer (current-buffer)))
    849           sexp
    850         ((:ok result)
    851          (when cont
    852            (if (buffer-live-p buffer)
    853                (progn
    854                  (set-buffer buffer)
    855                  (funcall cont result))
    856              (message
    857               "ENSIME: Asynchronous return could not find originating buffer.")
    858              )))
    859         ((:abort code reason)
    860          (message "Asynchronous RPC Aborted: %s" reason)))
    861       ;; Guard against arbitrary return values which once upon a time
    862       ;; showed up in the minibuffer spuriously (due to a bug in
    863       ;; ensime-autodoc.)  If this ever happens again, returning the
    864       ;; following will make debugging much easier:
    865       :ensime-eval-async)

I instrumented `ensime-eval-async` with `C-u C-M-x` and opened a new buffer. When `ensime-eval-async` was called, I dumped the `sexp` with `M-:`. 

It showed me `(swank:typecheck-file (:file "..."))`. 

The value of `cont` was `identity`.

**Comment by aemoncannon** [comment] 2015-11-09 20:57
Ok. Sounds like we've got a stray call to rpc-typecheck-file(s) passing a
file that doesn't exist. Server doesn't crash though, right?

**Comment by fommil** [comment] 2015-11-09 23:38
Our actor monitoring at the moment leaves a lot to be desired. I wouldn't be surprised if the actor dies and never restarts. We should really do better, especially with the Scala analyser.

**Comment by rahulkmr** [comment] 2015-11-10 09:00
@aemoncannon Yes, the server doesn't crash, and completion and checking works on the unsaved buffer.

**Comment by eddsteel** [comment] 2015-11-10 22:01
I'm getting this on a file that used to exist but has been moved (by someone else's commit). I still had an open buffer. The only difference compared to the example is this buffer won't ever be saved. Just raising it in case it needs to be handled differently (don't see why it would).

**Comment by fommil** [comment] 2015-11-10 22:06
@eddsteel  that sounds like you should set up magit to delete files under such situations. Bit of a corner case for us, I'm not sure we should have special logic for it to be honest.

**Comment by aemoncannon** [comment] 2015-11-10 22:09
As long as the buffer-file-name points to a connected project, we *should*
handle it correctly. I'm going to do an elisp test to exercise this case,
as it seems to be pretty common.

**Comment by eddsteel** [comment] 2015-11-10 22:12
@fommil the file's gone but not the buffer, and I can't find a way to make magit close buffers when files are deleted (maybe I'm not looking hard enough). Still, I think it falls into the "handle what buffer-file-name points to" category.

**Comment by fommil** [comment] 2015-11-10 22:16
@eddsteel yes, I think Emacs still believes that the buffer is attached to a file. If you want, send in a PR with an additional `(and ... (file-exists-p buffer-file-name))` check.

**Comment by eddsteel** [comment] 2015-11-10 22:48
Sorry, also a newb to the codebase, but now that I stop lazy-thinking and actually read the code I think @aemoncannon's fix covers it. I'm unsure about `ensime-rpc-async-typecheck-files` and `ensime-rpc-async-typecheck-file`. Should calls to these guard against buffers with no file?

**Comment by eddsteel** [comment] 2015-11-10 22:59
Confirmed that the fix is sufficient for my case. That elisp test definitely sounds worthwhile though. Sorry for the noise!

**Comment by fommil** [comment] 2015-11-11 07:25
Learning the code is never noise :smile:

**Comment by fommil** [comment] 2015-12-19 12:17
this should be fixed now, reopen if it still fails.

**Closed by fommil** 2015-12-19 12:17 UTC
