### ISSUE TITLE
ensime CPU when file get larger.

### ISSUE THREAD

**Issue by hiddenlotus** [ensime/ensime-emacs#204] opened 2015-07-25 15:05 UTC
Hi. First thanks for your terrific work. But I got some problems recently.
Currently I am working on a project of my company. 
When some files that less than 500 lines of code, everything seems work fine.
However when some file that contain over 2000 lines, the completion, type checker, navigation and even typing seems can not work.
The activity monitor shows that java %CPU is 292.3 and sometimes 400.
I use Emacs 24.5.1 on a MacBook with 2.7 GHz Intel Core i5 processor and 8 GB memory.
The ensime-sbt version is 0.1.7 and ensime version is 20150723.

**Comment by aemoncannon** [comment] 2015-07-25 15:26
Is it any large file, or just certain large files? We've had problems with
complicated uses of implicits choking the compiler.

**Comment by hiddenlotus** [comment] 2015-07-25 15:44
I think it's all large files.

**Comment by fommil** [comment] 2015-07-25 16:53
we're bound by the presentation compiler's performance at being able to handle large files. It is highly unusual to have files of that size in a scala codebase, so my first suggestion would be to refactor the code into smaller chunks. Your colleagues in Scala IDE are likely to be seeing the exact same problems.

I am, however, surprised that the CPU would go above 100% because the presentation compiler is single threaded. Perhaps you're sampling when the indexing phase is happening? (We max out the CPU during indexing, but it only takes a few minutes on first run).

If you could provide us with an example large file, perhaps from scanning github projects for a similar file, we could see if we're doing anything particularly costly that can be improved.

**Comment by fommil** [comment] 2015-07-25 16:56
@hiddenlotus btw, just so you don't feel we're blasting your code, you can have a look at this monstrosity to know that nobody is perfect :grin: https://github.com/ensime/ensime-server/blob/master/swank/src/main/scala/org/ensime/server/protocol/swank/SwankFormats.scala

Although, to demonstrate Aemon's point regarding implicits, this tiny file takes around a minute to compile so the presentation compiler doesn't stand a chance: https://github.com/ensime/ensime-server/blob/master/jerk/src/main/scala/org/ensime/jerk/JerkFormats.scala

**Comment by fommil** [comment] 2015-07-25 16:57
of relevance https://github.com/ensime/ensime-server/issues/954

**Comment by aemoncannon** [comment] 2015-07-25 17:08
Could you make a sample project that reproduces?

**Comment by hiddenlotus** [comment] 2015-07-26 04:31
I tested the two files.
https://github.com/ensime/ensime-server/blob/master/swank/src/main/scala/org/ensime/server/protocol/swank/SwankFormats.scala this file doesn't work. 
However https://github.com/ensime/ensime-server/blob/master/jerk/src/main/scala/org/ensime/jerk/JerkFormats.scala this tiny one works fine. 
 I will tell you if my colleagues' IDE work tomorrow, because today is Sunday in China.
I know we should keep the file small, but I don't know if I should change others' code..
And I send you some large file, please have a look. Thanks.

**Comment by fommil** [comment] 2015-07-26 08:58
@hiddenlotus yes, if you could send an example of your own files that would be good... we already know that the presentation compiler struggles with these two files. If you have big files doing lots of implicit stuff then it's probably the same problem.

**Comment by hiddenlotus** [comment] 2015-07-26 09:06
I sent you the file via your email in your github's profile page.

**Comment by fommil** [comment] 2015-07-26 09:15
@hiddenlotus is the file to be kept private? It would be a lot better if you could find a similar example on github because then we could use it as part of a test.

**Comment by fommil** [comment] 2015-07-26 09:21
@hiddenlotus interestingly, my emacs chokes a little bit on that file just in text mode. I wonder if the Chinese characters are somehow causing emacs trouble? In any case, there isn't much I can do with one file on its own, you'd have to find something in the OSS world that compiles. I'd still strongly suggest that you ask your colleagues if you can split the file into many parts (e.g. one file per method) as `trait`s and mix them together. Smaller files are a good thing because it allows the incremental compiler to optimise what needs to be recompiled on single character changes.

**Comment by hiddenlotus** [comment] 2015-07-26 11:52
It's my company's project, so I have to keep it private.
I will go on finding the reason.
Thank's for your patience and I would ask them to split the file. :smile:

**Comment by fommil** [comment] 2015-07-26 12:30
for now, we'll close as a dupe of the server ticket above.

**Closed by fommil** 2015-07-26 12:30 UTC
