### ISSUE TITLE
wrong number of argument when load .scala file

### ISSUE THREAD

**Issue by rexshihaoren** [ensime/ensime-emacs#518] opened 2016-09-04 17:50 UTC
### Steps to reproduce
With sbt installed and followed http://ensime.github.io/build_tools/sbt/#install
1. git clone https://github.com/rexshihaoren/progfun1.git
2. cd progfun1/example, sbt ensimeConfig
3. emacs progfun1/example
4. open any .scala file

### Expected behaviour

No abnormal messages

### Actual behaviour

"File mode specific error: wrong number of argument...."
![emacs](https://cloud.githubusercontent.com/assets/1203972/18231737/30d726ec-72f3-11e6-96ed-88e17efec29c.png)

**Comment by fommil** [comment] 2016-09-04 19:03
Did you follow the installation guide? You don't start the ensime server in your reproduction, unless you have some config to do that.

Do you know how to step debug in emacs? It might guide you to find and fix the problem.

**Comment by fommil** [comment] 2016-09-04 19:04
Looking at your debug trace, this doesn't look like an ensime problem... more likely it is something else in your config interfering with the scala major mode. Can you try to minimise a .emacs config that causes this?

**Comment by rexshihaoren** [comment] 2016-09-05 08:23
I am using el-get: https://gist.github.com/rexshihaoren/079fe1a592a8b2d4ba17293375def63a
This minimal init.el will produce the same error.

**Comment by fommil** [comment] 2016-09-05 08:28
that's probably the issue. We only recommend installation through `use-package` / MELPA. You'll probably get more response/help on the gitter channel. Closing since this isn't a bug in ensime.

**Closed by fommil** 2016-09-05 08:28 UTC
