### ISSUE TITLE
Buffer is read-only: #<buffer *ensime-search-results*>

### ISSUE THREAD

**Issue by casertap** [ensime/ensime-emacs#385] opened 2016-03-04 11:26 UTC
### Steps to reproduce

1. Have a sbt scala project open on emacs and connected ensime 
2. C-c C-v v
3. Type the name of the class, go on the filter window and hit RETURN to go to the source file

### Expected behaviour

I want to see the source of the selected file (The file exists, I have checked)

### Actual behaviour

It shows me the message:
```
Buffer is read-only: #<buffer *ensime-search-results*>
```

**Comment by fommil** [comment] 2016-03-04 11:28
thanks for following the template, but can you be a bit more specific about the steps? Example project, what is the search term, which one do you select, which file do you expect it to go to?

**Comment by casertap** [comment] 2016-03-04 11:33
Sorry.
I am inside of this project: https://github.com/RayRoestenburg/akka-in-action/tree/master/chapter-up-and-running

I open the src/main/scala/com/goticks/Main.scala
I set the cursor on line 30 on RestApi class name 
I hit C-c C-v v
I get 2 win windows (1 for filter, 1 to display the result)
I write: ActorSystem
The filter work so I move the cursor to the filter window and select: akka.actor.ActorSystem
I get the message: Buffer is read-only: #<buffer *ensime-search-results*> and nothing happen

**Comment by fommil** [comment] 2016-03-04 11:39
first two steps are irrelevant, search can happen anywhere. I'll try to reproduce tonight. Did you wait until indexing was completed?

**Comment by fommil** [comment] 2016-03-04 11:42
what happens if you go to line 27 and type `M-.` to go to the source of the `ActorSystem`. What does `C-c C-c v` print in the minibuffer?

Also, it is unusual to use the mouse to navigate the search results. Try just using the arrow keys (or `p`/`n`) and then using `RET` to select.

**Comment by casertap** [comment] 2016-03-04 11:51
When I hit ``` M-. ``` on ActorSystem I jump to the end of the Main.scala file.
My minibuffer says: ``` Buffer: *ensime-search-results* ```
I am not using the mouse. To get out of the window where I enter the "ActorSystem" text I use C-x o
Then I use C-p C-n once I am in the search result window but I can not select the file.
I get the same error has before

**Comment by casertap** [comment] 2016-03-04 11:53
Sorry ``` M-. ``` do works. Thanks
I still have the other problem but that is already good

**Comment by fommil** [comment] 2016-03-04 12:37
try doing it without `C-x o`

**Comment by fommil** [comment] 2016-03-04 12:40
if that works, this is potentially a dupe of https://github.com/ensime/ensime-emacs/issues/186

**Comment by casertap** [comment] 2016-03-04 12:57
When I am inside the search window, if I hit C-p or C-n I see the number of the line of the search result changing but no highlighting. 
I am still inside the search window, I hit RET but then all the search results disappear because the RETURN is included in the search.

**Comment by fommil** [comment] 2016-03-04 13:02
this works for me, I can't reproduce.

**Comment by casertap** [comment] 2016-03-04 13:03
ok I am using emacs 24.4.1 on debian over ssh. maybe this is causing the problem

**Comment by fommil** [comment] 2016-03-04 13:04
let's consider this a dupe of #186

**Closed by fommil** 2016-03-04 13:04 UTC

**Comment by casertap** [comment] 2016-03-06 21:57
I am just adding a comment here to add more info about the bug I encounter.
This guy here add the same issue with the Buffer is read-only error: https://www.emacswiki.org/emacs/EtagsSelect
I launch emacs inside of a iTerm, in a tmux session.

**Comment by rreckel** [comment] 2016-04-27 16:34
Hi @casertap 
I encounter the same problem, and I'm also using emacs in iTerm with a tmux session. (Really thought I would be the only one ;-))
For some reason, Emacs does not recognize the [(return)] key map.
I simply added the (kbd "RET") mapping in ensime-search-mode-map and ensime-search-target-buffer-map as follows:
(define-key map (kbd "RET") 'ensime-search-choose-current-result)
and now at least the choose-current-result function works again.

@fommil Could you please confirm the fix and perhaps include it in the next version?

Thx

**Comment by fommil** [comment] 2016-04-27 17:00
This was flagged as a dupe and I'd be happy to help you put together a pull request with a fix if you're confused about how to do that. It doesn't affect me so I won't be personally looking at it.

**Comment by casertap** [comment] 2016-04-27 22:29
Thanks @rreckel :-)

**Comment by rreckel** [comment] 2016-04-28 13:22
@fommil I just made a Pull Request to fix the "RET" key issue and also the highlighting....
It was my first Pull Request, so I hope everything was ok for you?!? (If not let me know)

As for #186, I would really love to see the search feature been integrated with helm, and perhaps even with helm-projectile ;-)
