### ISSUE TITLE
Updating server in ensime-startup.el does not work in my corporate environment

### ISSUE THREAD

**Issue by rstradling** [ensime/ensime-emacs#223] opened 2015-08-20 15:36 UTC
At my current company we do not have write or clone access to github.  I *believe* that is the issue I am running into.  I have installed everything as specified and when running ensime and choosing the ensime file I get an "exited abnormally with code 255" after it prints out "Updating ENSIME server".  I have tried to hack around such that it does not try to do the update but it has not worked.  I am completely fine if I need to install the ensime server myself.  I just don't know how to run the ensime server myself and to avoid this update.  Any help provided would be much appreciated.

**Comment by edani** [comment] 2015-08-20 16:14
ensime-update uses sbt to download the ensime binary distribution. So if you don't have sbt installed or you don't have access to the scala repositories, that might be the answer. You should be able to see more details about the error in a buffer named `*ensime-update*`

In any case, there should be a configuration to prevent the update but there isn't !   Until this is fixed, this workaround should work: in your .emacs, after  `(require 'ensime)` , add this:

```elisp
(defun ensime--update-server (scala-version on-success-fn)
      (funcall on-success-fn))
```

You still need to install the server, here are the instructions: https://github.com/ensime/ensime-emacs/wiki/Quick-Start-Guide#installing-the-server-from-source.   (once the ensime server is compilled  and you by pass the "ensime--update-server" function, things should w ork).  But for the compilation to work you still need access to github as well as scala package repositories.

**Comment by fommil** [comment] 2015-08-20 16:24
dupe of #154

**Closed by fommil** 2015-08-20 16:24 UTC

**Comment by fommil** [comment] 2015-08-20 16:26
without clone access to github, you'll struggle to follow those instructions. But hopefully you can download the zip (but then getting all the dependencies is going to be a pain).

#154 is really a placeholder for a more corporate friendly distribution. We need to reach the 1.0 milestone before it make sense to create a permanent release as we're currently on rolling release, however this may become a higher priority for me over the coming weeks in which case you'll see activity pretty quickly.

**Comment by rstradling** [comment] 2015-08-20 16:35
Ok.  Then I guess this is a dupe for the most part.  I can access the sbt repositories.  But to get to them with sbt I had to add to -Dhttp.proxyHost -Dhttps.proxyPort -Dhttp.proxyPort -Dhttps.proxyHost -Dhttp.nonProxyHosts to my _JAVA_OPTIONS environment variable.  Without that SBT could not download the resolvers.  However, I see in my .ensime file that java-flags is set and it has these options in there.  Any other thoughts as to why if sbt works (I can compile ensime-server fine as proof) but it does not work from emacs?

**Comment by fommil** [comment] 2015-08-20 16:35
@rstradling oh cool, if you have access to maven central, this gets a **lot** easier. So do you just not have access to sonatype snapshots?

**Comment by fommil** [comment] 2015-08-20 16:37
btw, you can also add that proxy config to your envvars. e.g. set 

```
http_proxy=http://localhost:3128/
ftp_proxy=http://localhost:3128/
https_proxy=https://localhost:3128/
no_proxy=... comma separated machine names, no wildcards unfortunately ...
```

**Comment by fommil** [comment] 2015-08-20 16:37
what does the `*ensime-update*` buffer say?

**Comment by rstradling** [comment] 2015-08-20 17:41
Wrote e:/cygwin64/tmp/ensime_update_19028jzI/build.sbt
Wrote e:/cygwin64/tmp/ensime_update_19028jzI/project/build.properties
Updating ENSIME server...
Process *ensime-update* exited: exited abnormally with code 255

Is in the *Messages* buffer

In the ensime-update buffer... it is empty.

**Comment by rstradling** [comment] 2015-08-20 18:12
Once in a while I also see this 
"| was unexpected at this time."

I saw it specifically the last time trying to run the following...
(start-process "*ensime-update*" (current-buffer) ensime-sbt-command "saveClasspath" "clean")

**Comment by fommil** [comment] 2015-08-20 21:24
It sounds like it's not finding SBT. Set the ensime-sbt-command to your SBT script.

**Comment by rstradling** [comment] 2015-08-21 00:48
Well it turns out that the version of SBT it was finding was SBT.bat.  When I ran the sbt.bat saveClasspath clean
I got the | was unexpected at this time

Right now I am trying to see if I can get it to recognize the SBT shell via cygwin

**Comment by yangguang760** [comment] 2017-01-20 06:13
Hi all,
I got similar issue under Linux.
when start ensime using M-x ensime, the ensime-update showed as the following:

```
Warning: could not parse http_proxy setting: java.net.MalformedURLException: no protocol: 192.168.8.26:8080
Warning: could not parse https_proxy setting: java.net.MalformedURLException: no protocol: 192.168.8.26:8080
Getting org.scala-sbt sbt 0.13.11 ...
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.

:: problems summary ::
:::: WARNINGS
	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.11/sbt-0.13.11.pom

	Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.11/sbt-0.13.11.jar

	Host repo.typesafe.com not found. url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.11/ivys/ivy.xml

	Host repo.scala-sbt.org not found. url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.11/ivys/ivy.xml

		module not found: org.scala-sbt#sbt;0.13.11

	==== local: tried

	  /home/yang/.ivy2/local/org.scala-sbt/sbt/0.13.11/ivys/ivy.xml

	  -- artifact org.scala-sbt#sbt;0.13.11!sbt.jar:

	  /home/yang/.ivy2/local/org.scala-sbt/sbt/0.13.11/jars/sbt.jar

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.11/sbt-0.13.11.pom

	  -- artifact org.scala-sbt#sbt;0.13.11!sbt.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.11/sbt-0.13.11.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.11/ivys/ivy.xml

	==== sbt-ivy-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.11/ivys/ivy.xml

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#sbt;0.13.11: not found

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;0.13.11: not found
Error during sbt execution: Error retrieving required libraries
  (see /home/yang/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.11

```

When using sbt, I could  use 
```
sbt  -Dhttp.proxyHost=192.168.8.26  -Dhttp.proxyPort=8080  -Dhttps.proxyHost=192.168.8.26  -Dhttps.proxyPort=8080
```

to make the proxy work.

**Comment by fommil** [comment] 2017-01-20 08:23
Dev ensime works differently so this isn't an issue anymore. There are docs on the website about corporate use.

**Comment by yangguang760** [comment] 2017-01-22 02:29
@fommil Would you please tell me the location of docs? I've searched through the website but did not find the docs.

**Comment by fommil** [comment] 2017-01-22 08:26
Look for assembly jars
