### ISSUE TITLE
Invalid rpc request (swank:type-at-point nil 929)

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-emacs#272] opened 2015-10-27 15:41 UTC
```
15:22:10.407 ERROR akka://ENSIME/user/ensime-main/tcp-server/con1 o.e.s.t.TCPConnectionActor - Error seen during message processing, closing client connection
org.ensime.server.protocol.swank.SwankRPCFormatException: Invalid rpc request (swank:type-at-point nil 929)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:877) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:866) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SwankProtocol.decode(SwankProtocol.scala:14) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.repeatedDecode(TCPConnectionActor.scala:106) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.attemptProcess(TCPConnectionActor.scala:95) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor$$anonfun$incoming$1.applyOrElse(TCPConnectionActor.scala:47) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.7.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]
	at org.ensime.server.tcp.TCPConnectionActor.aroundReceive(TCPConnectionActor.scala:15) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: org.ensime.sexp.DeserializationException: Unable to parse SexpNil
	at org.ensime.sexp.formats.package$.deserializationError(package.scala:5) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.StandardFormats$$anon$3.read(StandardFormats.scala:66) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:39) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:33) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$69.read(SwankFormats.scala:670) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$69.read(SwankFormats.scala:664) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:827) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:802) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$43.apply(SwankFormats.scala:871) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$43.apply(SwankFormats.scala:871) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.7.jar:na]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:871) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	... 18 common frames omitted
15:22:10.488 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/ensime-main/tcp-server/con1#1130809124]] terminated
```

**Comment by fommil** [comment] 2015-10-27 15:44
we'll need a test project or use case. looks like the query is missing the file.

**Comment by greenrd** [comment] 2015-11-13 10:09
This can happen if, in magit, you view an old file revision, and then press `M-.`. In other words, if the buffer doesn't have a file.

**Comment by fommil** [comment] 2015-11-13 10:25
dupe of #283

although for magit history, git-time-machine, and similar, we should probably disable `ensime-mode` as it causes other problems in the presentation compiler.

**Closed by fommil** 2015-11-13 10:25 UTC
